name: Build and Trigger Azure DevOps

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-trigger:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # OPTIONAL: Store the built artifacts in GitHub Actions
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorldBuild
          path: ./publish

      - name: Trigger Azure DevOps Deployment
        shell: pwsh
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Check Azure CLI version and add the azure-devops extension
          az --version
          az extension add --name azure-devops

          # Login to Azure DevOps using the PAT
          echo $env:AZURE_DEVOPS_PAT | az devops login --organization https://dev.azure.com/AcronoticsIP

          # Trigger the deployment pipeline (release) in Azure DevOps.
          # Replace "13749467692" with the artifact metadata value that you want to pass.
          az pipelines release create --artifact-metadata-list github_compass_artifacts="13749467692" --definition-id 23 --description "Triggered from Github" --detect false --org https://dev.azure.com/AcronoticsIP --project "RADIUM"
